name: My First Workflow
on: 
  push:
    branches: 
      - main
  workflow_dispatch:
jobs:
  MyFirstJob:
    runs-on: ubuntu-latest
    steps:
      - run: "echo Hola Fellas"
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: List files in directory
        run: |
          echo "The repository ${{ github.repository }} contains the following
          files:"
          tree
      

